import type { Character } from './types';

export const roster: Character[] = [
  { id: 'xerion', emoji: '🦂', portrait: '/images/characters/xerion.jpg', name: 'Xerion', species: 'Venomous scorpion', role: 'Poison · Attrition', personality: 'Cool-headed, cunning, and patient. He waits for an opening instead of wasting words on threats.', strength: 'Damage over time through poison', weakness: 'Low speed and a slow start', quote: 'Everything has an antidote. Except time.', hp: 96, attack: 7, defense: 6, speed: 5, special: 9, ability: 'Venom Strike', description: 'Deals steady damage, poisoning and slowing the opponent.', cooldown: 4 },
  { id: 'xylith', emoji: '🦗', portrait: '/images/characters/xylith.jpg', name: 'Xylith', species: 'Grasshopper', role: 'Speed · Counterattacks', personality: 'Hyperactive, witty, and always on the move. She never stays in one place for long.', strength: 'Speed and evading attacks', weakness: 'Below-average defense', quote: 'Catch me first!', hp: 96, attack: 7, defense: 5, speed: 10, special: 8, ability: 'Phantom Leap', description: 'Gains a chance to dodge an attack and counter if successful.', cooldown: 4 },
  { id: 'xarok', emoji: '🪲', portrait: '/images/characters/xarok.jpg', name: 'Xarok', species: 'Rhinoceros beetle', role: 'Tank · Defense', personality: 'Quiet, patient, and unshakable. He never backs down without a reason.', strength: 'High health and damage reduction', weakness: 'Low speed; vulnerable to damage over time', quote: 'A wall does not fall just because you push it.', hp: 120, attack: 7, defense: 8, speed: 3, special: 7, ability: 'Iron Carapace', description: 'Reduces direct damage taken by 28% for two turns.', cooldown: 6 },
  { id: 'xyra', emoji: '🕷️', portrait: '/images/characters/xyra.jpg', name: 'Xyra', species: 'Spider', role: 'Control · Traps', personality: 'Manipulative and observant. She tries to read her opponent before they act.', strength: 'Crowd control and interrupting a turn', weakness: 'Average while her ability is on cooldown', quote: 'Seeing my web does not mean you can escape it.', hp: 99, attack: 7, defense: 6, speed: 6, special: 9, ability: 'Web Snare', description: 'Deals damage and stops the opponent’s next action.', cooldown: 8 },
  { id: 'xenith', emoji: '🦟', portrait: '/images/characters/xenith.jpg', name: 'Xenith', species: 'Mosquito', role: 'Lifesteal · Attrition', personality: 'Brazen, persistent, and irritating. She loves getting under her opponent’s skin.', strength: 'Restores health while dealing damage', weakness: 'Lacks high burst damage', quote: 'Hear that? I’m still here.', hp: 100, attack: 6, defense: 6, speed: 8, special: 8, ability: 'Blood Drain', description: 'Deals damage and restores 65% of it as health.', cooldown: 4 },
  { id: 'xull', emoji: '🐜', portrait: '/images/characters/xull.jpg', name: 'Xull', species: 'Ant', role: 'Multi-hit · Pressure', personality: 'Disciplined and mission-focused. A collective intelligence that moves as one.', strength: 'Multiple hits in a single turn', weakness: 'Individual hits are weaker against high defense', quote: 'Not me. Us.', hp: 100, attack: 7, defense: 7, speed: 5, special: 8, ability: 'Swarm Overload', description: 'Delivers three quick attacks in one turn.', cooldown: 4 },
  { id: 'xelthar', emoji: '👽', portrait: '/images/characters/xelthar.jpg', name: 'Xel’thar', species: 'Crystal alien', role: 'Burst · Energy', personality: 'Cold, analytical, and arrogant. He believes everything can be calculated.', strength: 'High single-target damage and critical chance', weakness: 'Low health and defense', quote: 'I calculated the outcome. Try not to delay it.', hp: 88, attack: 9, defense: 4, speed: 6, special: 9, ability: 'Prism Beam', description: 'A high-critical energy attack that partially pierces defense.', cooldown: 5 },
  { id: 'xyvora', emoji: '👾', portrait: '/images/characters/xyvora.jpg', name: 'Xyvora', species: 'Plasma mutant', role: 'Chaos · Adaptation', personality: 'Chaotic, curious, and unpredictable. Even she is surprised by her transformations.', strength: 'Can adapt stats to the flow of battle', weakness: 'One stat rises while another falls', quote: 'Which version of me wins this time?', hp: 104, attack: 8, defense: 7, speed: 7, special: 10, ability: 'Chaos Shift', description: 'Randomly boosts one stat and lowers another for three turns.', cooldown: 4 },
];
