import type { Character } from './types';

export const roster: Character[] = [
  { id: 'xerion', emoji: '🦂', portrait: '/images/characters/xerion.jpg', name: 'Xerion', species: 'Zehirli akrep', role: 'Zehir · Uzun maç', personality: 'Soğukkanlı, sinsi ve sabırlı. Tehdit savurmak yerine rakibinin açığını bekler.', strength: 'Zehirle zamana yayılan hasar', weakness: 'Düşük hız ve yavaş başlangıç', quote: 'Her şeyin bir panzehiri vardır. Zaman hariç.', hp: 96, attack: 7, defense: 6, speed: 5, special: 9, ability: 'Venom Strike', description: 'Dengeli hasar verir; zehir ve yavaşlatma uygular.', cooldown: 4 },
  { id: 'xylith', emoji: '🦗', portrait: '/images/characters/xylith.jpg', name: 'Xylith', species: 'Çekirge', role: 'Hız · Karşı saldırı', personality: 'Hiperaktif, alaycı ve hareketli. Bir an bile aynı yerde kalmaz.', strength: 'Hız ve saldırılardan kaçınma', weakness: 'Savunması ortalamanın altında', quote: 'Yetişebilirsen konuşuruz!', hp: 96, attack: 7, defense: 5, speed: 10, special: 8, ability: 'Phantom Leap', description: 'Saldırıdan sıyrılma şansı kazanır; kaçarsa karşılık verir.', cooldown: 4 },
  { id: 'xarok', emoji: '🪲', portrait: '/images/characters/xarok.jpg', name: 'Xarok', species: 'Gergedan böceği', role: 'Tank · Savunma', personality: 'Sessiz, sabırlı ve sarsılmaz. Gereksiz yere geri adım atmaz.', strength: 'Yüksek can ve güçlü hasar azaltma', weakness: 'Düşük hız; zehir gibi sürekli etkiler', quote: 'Duvarı zorlamak, duvarı yıkmaz.', hp: 120, attack: 7, defense: 8, speed: 3, special: 7, ability: 'Iron Carapace', description: 'İki tur boyunca aldığı doğrudan hasarı %28 azaltır.', cooldown: 6 },
  { id: 'xyra', emoji: '🕷️', portrait: '/images/characters/xyra.jpg', name: 'Xyra', species: 'Örümcek', role: 'Kontrol · Tuzak', personality: 'Manipülatif ve gözlemci. Rakibinin kararlarını önceden okumaya çalışır.', strength: 'Kontrol ve rakibin turunu kesme', weakness: 'Yetenek beklemedeyken ortalama kalır', quote: 'Ağımı görmen, içinden çıkabileceğin anlamına gelmez.', hp: 99, attack: 7, defense: 6, speed: 6, special: 9, ability: 'Web Snare', description: 'Hasar verir ve rakibin sonraki eylemini durdurur.', cooldown: 8 },
  { id: 'xenith', emoji: '🦟', portrait: '/images/characters/xenith.jpg', name: 'Xenith', species: 'Sivrisinek', role: 'Can çalma · Yıpratma', personality: 'Küstah, ısrarcı ve sinir bozucu. Rakibini kızdırmayı sever.', strength: 'Hasar verirken canını geri kazanır', weakness: 'Yüksek burst hasarı yoktur', quote: 'Duydun mu? Ben hâlâ buradayım.', hp: 100, attack: 6, defense: 6, speed: 8, special: 8, ability: 'Blood Drain', description: 'Hasar verir ve hasarın %65’ini can olarak geri alır.', cooldown: 4 },
  { id: 'xull', emoji: '🐜', portrait: '/images/characters/xull.jpg', name: 'Xull', species: 'Karınca', role: 'Çoklu saldırı · Baskı', personality: 'Disiplinli ve görev odaklı. Birlikte hareket eden bir kolektif zekâdır.', strength: 'Bir turda birden fazla vuruş', weakness: 'Savunması yüksek rakibe karşı vuruşları zayıflar', quote: 'Ben değil. Biz.', hp: 100, attack: 7, defense: 7, speed: 5, special: 8, ability: 'Swarm Overload', description: 'Aynı turda üç hızlı saldırı yapar.', cooldown: 4 },
  { id: 'xelthar', emoji: '👽', portrait: '/images/characters/xelthar.jpg', name: 'Xel’thar', species: 'Kristal uzaylı', role: 'Burst · Enerji', personality: 'Soğuk, analitik ve üstünlük taslayan. Her şeyi hesaplanabilir görür.', strength: 'Yüksek tek hedef hasarı ve kritik şansı', weakness: 'Düşük can ve savunma', quote: 'Sonucu hesapladım. Sen yalnızca gecikmesin.', hp: 88, attack: 9, defense: 4, speed: 6, special: 9, ability: 'Prism Beam', description: 'Savunmayı kısmen delen, kritik şansı yüksek bir enerji saldırısı yapar.', cooldown: 5 },
  { id: 'xyvora', emoji: '👾', portrait: '/images/characters/xyvora.jpg', name: 'Xyvora', species: 'Plazma mutantı', role: 'Kaos · Adaptasyon', personality: 'Kaotik, meraklı ve öngörülemez. Kendi değişimlerine bile şaşırır.', strength: 'Savaşın akışına göre statlarını değiştirebilir', weakness: 'Bir statı artarken diğeri düşer', quote: 'Bu sefer hangi ben kazansın?', hp: 104, attack: 8, defense: 7, speed: 7, special: 10, ability: 'Chaos Shift', description: 'Üç tur için rastgele bir statı güçlü biçimde artırıp diğerini düşürür.', cooldown: 4 },
];
